name: Triggered Workflow

on:
  repository_dispatch:
    types:
      - trigger-event

jobs:
  build-docker-producer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build producer
        run: |
          docker build -t producer:1.0 -f docker/Dockerfile.producer .
          docker run --rm producer:1.0
